### ISSUE TITLE
Implement sticky session support based on design

### ISSUE THREAD

**Issue by timh** [heptio/contour#1006]
Implement sticky session support based on design in PR #1005

**Comment by davecheney** [comment]
A design draft for how we plan to implement this feature was added in #1005. TL;DR
```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: httpbin
  namespace: default
spec:
  virtualhost:
    fqdn: httpbin2.davecheney.com
  routes:
  - match: /
    services:
    - name: httpbin
      port: 8080
      strategy: cookie
```
The `strategy: cookie` setting tells Envoy to use a cookie that it manages itself to route requests to the same backend.
