### ISSUE TITLE
Possible issue with Ingress rules not routing?

### ISSUE THREAD

**Issue by adelbertc** [heptio/contour#101]
Running on K8s 1.8.4 + RBAC through OpenStack, LoadBalancer support (I think..), I re-deployed Contour just now to make sure I was on a new version of Contour too. Testing out a simple rule. 

This Ingress definition works, confirmed with `curl -i http://<LB IP>`:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello
  labels:
    app: hello
spec:
  backend:
    serviceName: hello
    servicePort: 80
```

This however does not, giving instead a 404 when I `curl -i http://<LB IP>/hello`:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello
  labels:
    app: nelson
spec:
  rules:
    - http:
        paths:
          - path: /hello
            backend:
              serviceName: hello
              servicePort: 80
```

Here are the Deployment and Service objects I'm using:

```yaml
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    app: hello
    version: v1
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        version: v1
      name: hello
    spec:
      containers:
        - name: hello
          image: gcr.io/hightowerlabs/server:0.0.1
          imagePullPolicy: Always
          args:
            - "-name=istio-test-v1"
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    app: hello
  type: ClusterIP
```

**Comment by davecheney** [comment]
@adelbertc thanks for raising the issue. I have a feeling I know what it is. 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello
  labels:
    app: nelson
spec:
  rules:
    - http:
        paths:
```
Doesn't specify a hostname. https://kubernetes.io/docs/api-reference/v1.8/#ingressrule-v1beta1-extensions (the `host:` field).

Contour expects this field to be mandatory, but I'll check the api definitions for 1.8 and confirm this. 

In the meantime the workaround would be to add a `host:` field to your ingress object.
