### ISSUE TITLE
Contour sends invalid configuration to Envoy when TLS secret is not well formed.

### ISSUE THREAD

**Issue by mattmoyer** [heptio/contour#1051]
We are running into an issue using Contour with [cert-manager](https://github.com/jetstack/cert-manager).

The setup:
- We create a cert-manager Certificate object.
- The cert-manager controller provisions a private key and starts requesting the certificate from Let's Encrypt.
- It saves the private key into the certificate Secret, in the following form:
   ```yaml
   apiVersion: v1
   kind: Secret
   metadata:
     name: my-tls-secret
     namespace: my-namespace
     labels:
       certmanager.k8s.io/certificate-name: my-tls-cert
   type: kubernetes.io/tls
   data:
     ca.crt: null
     tls.crt: null
     tls.key: # a valid base64 encoded private key [....]
   ```
- Let's Encrypt denies our certificate request based on their rate limiting policy, so the Secret stays in this half-created state for an extended period of time.
- Contour sees that the Ingress and associated Secret exist, and attempts to configure Envoy with the new values.
- Envoy rejects the configuration and emits an error log:
   ```
   [2019-04-26 16:32:29.677][000001][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Proto constraint validation failed (ListenerValidationError.FilterChains[i]: ["embedded message failed validation"] | caused by FilterChainValidationError.TlsContext: ["embedded message failed validation"] | caused by DownstreamTlsContextValidationError.CommonTlsContext: ["embedded message failed validation"] | caused by CommonTlsContextValidationError.TlsCertificates[i]: ["embedded message failed validation"] | caused by TlsCertificateValidationError.CertificateChain: ["embedded message failed validation"] | caused by field: "specifier", reason: is required): name: "ingress_https"
   ```
- It then dumps the entire configuration including private keys to the log file 😬. The `tls_context` section that I think is causing problems looks like this (note empty `certificate_chain` field):
   ```
   filter_chains {
     filter_chain_match {
       server_names: "myhost.example.com"
     }
     tls_context {
       common_tls_context {
         tls_params {
           tls_minimum_protocol_version: TLSv1_1
           tls_maximum_protocol_version: TLSv1_3
         }
         tls_certificates {
           certificate_chain {
           }
           private_key {
             inline_bytes: "-----BEGIN RSA PRIVATE KEY-----[...]-----END RSA PRIVATE KEY-----\n"
           }
         }
         alpn_protocols: "h2"
         alpn_protocols: "http/1.1"
       }
     }
   [...]
   ```

Once we're in this state, Envoy's configuration is frozen in time and does not follow new Ingress/Endpoint updates. If the Envoy/Contour pod restarts for any reason, it will fail to come back online at all.
