### ISSUE TITLE
ds-hostnet-split example refers to undefined CONTOUR_SERVICE and CONTOUR_PORT variables

### ISSUE THREAD

**Issue by bgagnon** [heptio/contour#1122]
The variables `CONTOUR_SERVICE_HOST` and `CONTOUR_SERVICE_PORT` are not defined anywhere, but used

...in `deployment/ds-hostnet-split/03-envoy.yaml`:

```yaml
initContainers:
      - args:
        - bootstrap
        - /config/contour.json
        - --xds-address
        - $(CONTOUR_SERVICE_HOST)
        - --xds-port
        - $(CONTOUR_SERVICE_PORT)
        command:
        - contour
        image: gcr.io/heptio-images/contour:master
```

...and `deployment/ds-hostnet-split/03-contour.yaml`:

```yaml
      containers:
      - args:
        - serve
        - --incluster
        - --xds-address=0.0.0.0
        - --xds-port=$(CONTOUR_SERVICE_PORT)
        - --envoy-service-http-port=80
        - --envoy-service-https-port=443
        command: ["contour"]
        image: gcr.io/heptio-images/contour:master
```

I've replaced them with `contour` and `8001`, respectively.
Is the idea that these should come from a common `ConfigMap`?
