### ISSUE TITLE
example/ switch to downstream API and env var for Envoy's --service-cluster and --service-node flags

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#1244]
Envoy mandates the `--service-cluster` and `--service-node` flags be present. As these flags appear mandatory, we hard code them to dummy values in all our `examples/`.

Recently @stevesloka pointed out, https://github.com/heptio/contour/issues/1130#issuecomment-509643704, that it is possible to use the downstream API and env vars in deployments. I've done some quick tests and it appears to be possible to plumb the namespace and pod name into the `--service-cluster` and `--service-node` flags respectively.
```yaml
      - args:
        - --config-path /config/contour.json
        - --service-cluster $(CONTOUR_NAMESPACE)
        - --service-node $(ENVOY_POD_NAME)
        - --log-level info
        command:
        - envoy
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ENVOY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```
I recommend we should update our `examples/` to use this pattern throughout to pass useful data from the Envoy clients which we are currently squandering.
