### ISSUE TITLE
Contour 0.14 examples - cannot create log

### ISSUE THREAD

**Issue by so0k** [heptio/contour#1279]
**What steps did you take and what happened:**
Deployed Contour as ds-hostnet-combined:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: "2019-07-26T10:34:16Z"
  generation: 1
  labels:
    app: contour-internal
    chart: contour-0.4.0
    component: router
    heritage: Tiller
    release: contour-internal
  name: contour-internal
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: contour-internal
      component: router
      release: contour-internal
  template:
    metadata:
      annotations:
        ad.datadoghq.com/contour.check_names: |
          [
            "prometheus"
          ]
        ad.datadoghq.com/contour.init_configs: |
          [
            {}
          ]
        ad.datadoghq.com/contour.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:8000/metrics",
              "namespace": "contour",
              "metrics": ["contour_*"]
            }
          ]
        ad.datadoghq.com/contour.logs: |
          [
            {
              "source":"contour",
              "service":"ingress"
            }
          ]
        ad.datadoghq.com/envoy.check_names: |
          [
            "envoy"
          ]
        ad.datadoghq.com/envoy.init_configs: |
          [
            {}
          ]
        ad.datadoghq.com/envoy.instances: |
          [
            {
              "stats_url": "http://%%host%%:8002/stats"
            }
          ]
        ad.datadoghq.com/envoy.logs: |
          [
            {
              "source":"envoy",
              "service":"ingress"
            }
          ]
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      creationTimestamp: null
      labels:
        app: contour-internal
        chart: contour-0.4.0
        component: router
        heritage: Tiller
        release: contour-internal
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/spot-edge
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: Exists
      automountServiceAccountToken: true
      containers:
      - args:
        - -c
        - /config/contour.json
        - --service-cluster
        - envoy-cluster
        - --service-node
        - $(NODE_NAME)
        - --base-id
        - "1"
        command:
        - envoy
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.io/envoyproxy/envoy-alpine:v1.10.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - wget
              - -qO-
              - http://localhost:9001/healthcheck/fail
        name: envoy
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          hostPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8002
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: contour-config
      - args:
        - serve
        - --incluster
        - --xds-port
        - "8001"
        - --http-port
        - "8000"
        - --stats-port
        - "8002"
        - --envoy-service-http-port
        - "8080"
        - --envoy-service-https-port
        - "8443"
        - --ingress-class-name=contour-internal
        command:
        - contour
        image: gcr.io/heptio-images/contour:v0.14.0
        imagePullPolicy: IfNotPresent
        name: contour
        ports:
        - containerPort: 8001
          hostPort: 8001
          name: xds
          protocol: TCP
        - containerPort: 8000
          hostPort: 8000
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
      - args:
        - bootstrap
        - /config/contour.json
        - --xds-port
        - "8001"
        - --admin-port
        - "9001"
        command:
        - contour
        image: gcr.io/heptio-images/contour:v0.14.0
        imagePullPolicy: IfNotPresent
        name: envoy-initconfig
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: contour-config
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: contour-internal
      serviceAccountName: contour-internal
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: spotInstance
      - effect: NoSchedule
        key: edge
      volumes:
      - emptyDir: {}
        name: contour-config
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 33%
    type: RollingUpdate
```

It worked for a while, then envoy lost gRPC connection:

```shell
[2019-07-26 14:39:34.267][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
[2019-07-26 14:39:34.413][1][info][upstream] [source/server/lds_api.cc:66] lds: remove listener 'ingress_https'
[2019-07-26 14:39:34.469][1][info][upstream] [source/server/lds_api.cc:74] lds: add/update listener 'ingress_https'
```

investigation shows contour restarted - with `kubectl logs -c contour -p` showing:

```shell
time="2019-07-26T13:35:02Z" level=info msg=response connection=6 context=grpc count=1 error_detail=nil resource_names="[ingress_https]" response_nonce=7 type_url=type.googleapis.com/envoy.api.v2.RouteConfiguration version_info=7
time="2019-07-26T13:35:02Z" level=info msg=stream_wait connection=6 context=grpc error_detail=nil resource_names="[ingress_https]" response_nonce=2 type_url=type.googleapis.com/envoy.api.v2.RouteConfiguration version_info=2
W0726 14:39:33.851239       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: watch of *v1beta1.Ingress ended with: too old resource version: 153445 (182755)
log: exiting because of error: log: cannot create log: open /tmp/contour.ip-10-50-176-240.unknownuser.log.WARNING.20190726-143933.1: no such file or directory
```

**What did you expect to happen:**
Contour should not crash

**Anything else you would like to add:**
Perhaps we should add the `/tmp` emptyDir mount to the example manifests?

**Environment:**

- Contour version: 0.14 / Envoy 1.10
- Kubernetes version: (use `kubectl version`): 1.13-eks
- Kubernetes installer & version: eks
- Cloud provider or hardware configuration: AWS - latest EKS optimized AMIs 
- OS (e.g. from `/etc/os-release`): Amazon Linux 2
