### ISSUE TITLE
default ingress appears on ingress_https

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#129]
This ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kuard
          servicePort: 80
```
Will register the route on ingress_https even though it has not hostname or TLS stanza. This should not happen.
