### ISSUE TITLE
Partial configuration in the config file is not defaulted correctly for child structs

### ISSUE THREAD

**Issue by youngnick** [heptio/contour#1367]
# What happened
When prototyping putting leader election configuration in the configuration file, I found the following import from YAML did not work as I expected.

For the following struct:
```go
type LeaderElectionConfig struct {
	LeaseDuration time.Duration `yaml:"lease-duration"`
	RenewDeadline time.Duration `yaml:"renew-deadline"`
	RetryPeriod   time.Duration `yaml:"retry-period"`
	Namespace     string        `yaml:"configmap-namespace"`
	Name          string        `yaml:"configmap-name"`
}
```
This struct is included under a YAML field of `leaderelection`. So a full config, set to the defaults set elsewhere in `cmd/contour/serve.go` would look like this:
```yaml
leaderelection:
  lease-duration: 15s
  renew-deadline: 10s
  retry-period: 2s
  configmap-name: contour
  configmap-namespace: heptio-contour
```

This would produce a `LeaderElectionConfig` struct that had everything set correctly.

However, the following snippet:

```yaml
leaderelection:
  configmap-name: contour
  configmap-namespace: heptio-contour

```

Would produce a `LeaderElectionConfig` with only the `Namespace` and `Name` fields set, and the `time.Duration` fields set to their zero value. As there is no further input sanitation in the leader election code, this will produce a panic when used.

# What I expected

I expected that I would only need to set items I wished to change from defaults (in this case, `Name` and `Namespace`), and that defaults would be populated without needing to be in the configuration file.
