### ISSUE TITLE
Invalid IngressRoute with TLS still results in open HTTP listener

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#1452]
This issue is related to #1348

**What steps did you take and what happened:**
1. Create a secret in the `heptio-contour` namespace
2. Create an app with the following IngressRoute. Note that the IngressRoute references a TLS certificate in another namespace:

```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: app-with-tls-delegation
  namespace: app-with-tls-delegation
spec:
  virtualhost:
    fqdn: app-with-tls-delegation.127.0.0.1.nip.io
    tls:
      secretName: heptio-contour/ssl-cert
  routes:
  - match: '/'
    services:
    - name: app-with-tls-delegation
      port: 80
```

3. Get the IngressRoute and check the status. Notice how the IngressRoute is deemed invalid:

```shell
NAME                      FQDN                                       TLS SECRET                FIRST ROUTE   STATUS    STATUS DESCRIPTION
app-with-tls-delegation   app-with-tls-delegation.127.0.0.1.nip.io   heptio-contour/ssl-cert   /             invalid   heptio-contour/ssl-cert: certificate delegation not permitted

```

4. Access the application on the insecure port:

```shell
$ kubectl -n heptio-contour port-forward envoy-5d699 8080:80 &
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80

$ curl -I app-with-tls-delegation.127.0.0.1.nip.io:8080
Handling connection for 8080
HTTP/1.1 200 OK
server: envoy
date: Thu, 05 Sep 2019 13:37:28 GMT
content-type: text/html
content-length: 612
last-modified: Tue, 13 Aug 2019 08:50:00 GMT
etag: "5d5279b8-264"
accept-ranges: bytes
x-envoy-upstream-service-time: 1

```

**What did you expect to happen:**
According to the documentation, the insecure port should be redirecting traffic to the secure port. I am not getting a redirect though.
> Contour also follows a "secure first" approach. When TLS is enabled for a virtual host, any request to the insecure port is redirected to the secure interface with a 301 redirect.

**Anything else you would like to add:**
The DAG:
```
digraph DAG {
rankdir="LR"
"0xc000654360" [shape=record, label="{listener|:80}"]
"0xc00064dd80" [shape=record, label="{http://app-with-tls-delegation.127.0.0.1.nip.io}"]
"0xc0003bec30" [shape=record, label="{prefix|/}"]
"0xc0006542a0" [shape=record, label="{cluster|{app-with-tls-delegation/app-with-ef7df1/80/da39a3ee5e|weight 0}}"]
"0xc000178c40" [shape=record, label="{service|app-with-tls-delegation/app-with-tls-delegation:80}"]
"0xc0006542a0" -> "0xc000178c40"
"0xc0003bec30" -> "0xc0006542a0"
"0xc00064dd80" -> "0xc0003bec30"
"0xc000654360" -> "0xc00064dd80"
}
```

Envoy's config dump:
https://gist.github.com/alexbrand/e299e7d6f22c9dd61d3d538296efbefb

**Environment:**

- Contour version: 
```
Name                       Image
contour-794b5558f6-8vn9h   projectcontour/contour:master
contour-794b5558f6-pgcm5   projectcontour/contour:master
contour-certgen-j29jk      projectcontour/contour:master
envoy-5d699                docker.io/envoyproxy/envoy:v1.11.1
envoy-f56fm                docker.io/envoyproxy/envoy:v1.11.1
envoy-k6bjs                docker.io/envoyproxy/envoy:v1.11.1
```
