### ISSUE TITLE
Regression with path-based routing and editing ingresses in 0.3.0

### ISSUE THREAD

**Issue by adelbertc** [heptio/contour#172]
I followed the RBAC instructions here https://github.com/heptio/contour#add-contour-to-your-cluster which I believe should pull in the latest 0.3.0.

I previously filed an issue https://github.com/heptio/contour/issues/101 with path-based routing when the host was missing, this was later fixed and confirmed on my end.

Today I was debugging some stuff on what I believe is 0.3.0 which per the commit log should include the fix, but it seems to be broken again. Here's what I tried..

1. Deploy kuard with (adapted from the kuard YAML file in README, removing the ingress)

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
```

2. Add the single service ingress rule, no host:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  backend:
    serviceName: kuard
    servicePort: 80
```

3. `curl -i <load balancer address>` from outside works. Doing `kubectl describe ing kuard` shows (omitting IP addresses, but they're there)

```
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     kuard:80 (..., ..., ...) 
Annotations:
Events:  <none>
```

4. Remove the single service ingress rule (editing seems to not update Contour, more below), and apply one based on paths:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  rules:
  - http:
      paths:
      - path: /testing
        backend:
          serviceName: kuard
          servicePort: 80
```

5. `curl -i <load balancer address>/testing` gives 404. Moreover doing `kubectl describe ing kuard` gives

```
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     
        /testing   kuard:80 (<none>)
Annotations:
Events:  <none>
```

6. To add to the weirdness, editing the path-based file to match the single service one and `kubectl apply -f`-ing it which as far as I know should update it still causes a 404, but describe gives the expected result with the IP addresses listed.

**Comment by davecheney** [comment]
Thanks for the detailed bug report, it's the weekend here, I'll take a look on monday.

**Comment by davecheney** [comment]
The short answer is the default vhost is complicated. I'm still working on figuring out the edge cases.

**Comment by adelbertc** [comment]
@davecheney Tried pointing an A record at it and using host

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  rules:
  - host: <removed, but it's there>
    http:
      paths:
      - path: /foo
        backend:
          serviceName: kuard
          servicePort: 80
```

But no go. It hits Envoy but seems to route incorrectly:

```
$ ⊢ curl -i <removed>/foo
HTTP/1.1 404 Not Found
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Sat, 20 Jan 2018 01:18:12 GMT
content-length: 19
x-envoy-upstream-service-time: 0
server: envoy

404 page not found
```

**Comment by davecheney** [comment]
Can you check the logs from your contour container `kubectl -n
heptio-contour logs -c contour $POD`, my guess is it's reporting something
about a duplicate default host.

**Comment by davecheney** [comment]
@adelbertc thank you for your detailed bug report. I spent today building a test harness, #177 , but so far have not been able to reproduce the problem you reported. In effect, editing an existing ingress, seems to cause the correct result in the gRPC configuration sent to envoy.

Can I ask you to do some more debugging if you are able to reproduce the issue.

1. Tail the log of a envoy pod before making the edit
 ```
% kubectl -n heptio-contour -c envoy logs $POD -f
```
2. Make the edit and make sure that envoy does not report any errors with the configuration. If it does, please report them here.

**Comment by davecheney** [comment]
Btw, which kubernetes version are you using?

**Comment by davecheney** [comment]
Also, when you say the edit failed. Can you please confirm this by doing `kubectl get -o yaml` and confirm your edit was or was not applied. Thanks.

**Comment by adelbertc** [comment]
I am on Kubernetes 1.8.x. I am checking logs, nothing out of the ordinary thus far.

**Comment by adelbertc** [comment]
@davecheney I now wonder, Contour aside, with just the Ingress object, if I see a list of backends when I have a single service ingress rule and no backends with path-based ingress rules, that seems to suggest an issue with my Kubernetes installation as opposed to a Contour issue...

**Comment by davecheney** [comment]
@adelbertc could you show what you're talking about in yaml?

**Comment by adelbertc** [comment]
With this Ingress definition:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  backend:
    serviceName: kuard
    servicePort: 80
```

I get this output this `kubectl describe`:

```yaml
Name:             kuard
Namespace:        dev
Address:          
Default backend:  kuard:80 (<list of IP addresses>)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     *     kuard:80 (<list of IP addresses>)
Annotations:
Events:  <none>
```

However with this YAML (making sure to delete the previous Ingress definition first):

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  rules:
    - http:
        paths:
          - path: /testing
            backend:
              serviceName: kuard
              servicePort: 80
```

I get this (note no backends):

```
Name:             kuard
Namespace:        dev
Address:          
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *     
        /testing   kuard:80 (<none>)
Annotations:
Events:  <none>
```

**Comment by davecheney** [comment]
I don't know where describe gets that information from, I'll have to read it's source. 

I wouldn't treat this line
```
Default backend:  default-http-backend:80 (<none>)
```
As being authoritative.

**Comment by davecheney** [comment]
Based on my reading of how describe works for Ingress objects, this behaviour is expected
```
                def := ing.Spec.Backend
                ns := ing.Namespace
                if def == nil {
                        // Ingresses that don't specify a default backend inherit the
                        // default backend in the kube-system namespace.
                        def = &extensions.IngressBackend{
                                ServiceName: "default-http-backend",
                                ServicePort: intstr.IntOrString{Type: intstr.Int, IntVal: 80},
                        }
                        ns = metav1.NamespaceSystem
                }
                w.Write(LEVEL_0, "Default backend:\t%s (%s)\n", backendStringer(def), i.describeBackend(ns, def))
```
and unrelated to Contour.

**Comment by adelbertc** [comment]
Right, I was more alluding to the backends listed (or not listed) under the Rules section, I assume should have the expected behavior. However looks like with path-based routing no backend is picked up.

Either way, doesn't seem to be a Contour issue at the moment, especially considering you tested on your end with a test harness. Probably an issue on my end, closing for now - thank you!

**Comment by davecheney** [comment]
Thanks for confirming.

**Comment by james-xiang** [comment]
@adelbertc I am doing the exact same testing with what you were doing.  I am using the image: gcr.io/heptio-images/contour:master.  I got the same problem which path based rule doesn't work as I expected. 

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  rules:
  - host: aptgw.test.com
    http:
      paths:
      - path: /kuard
        backend:
          serviceName: kuard
          servicePort: 80

```
kubectl describe shows:
`kubectl describe ing/kuard
Name:             kuard
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host            Path  Backends
  ----            ----  --------
  aptgw.test.com
                  /kuard   kuard:80 (<none>)
Annotations:
Events:  <none>
`
It seems contour doesn't pick up the backend specified in rules.
