### ISSUE TITLE
Using a named targetPort in application Service breaks Contour

### ISSUE THREAD

**Issue by sgringwe** [heptio/contour#175]
Kubernetes version 1.8.5-gke.0 on GKE

Using a named port like below for the targetPort results in "no healthy upstream" error.

```
apiVersion: v1
kind: Service
metadata:
  name: specs-web-service
  namespace: specs
  labels:
    app: specs
    tier: web
spec:
  type: NodePort
  ports:
  - name: specs-web-service-port
    port: 80
    protocol: TCP
    targetPort: http-server
  selector:
    app: specs
    tier: web
```

Changing "http-server" to "8080" resolves the issue immediately.
