### ISSUE TITLE
Find a way to allow xds_cluster to be defined as a DNS name, not an IP address

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#228]
Using `contour bootstrap --xds-address=contour.heptio-contour.svc.cluster.local` causes the following bootstrap config to be written.
```
dynamic_resources:
  lds_config:
    api_config_source:
      api_type: GRPC
      cluster_names: [xds_cluster]
      grpc_services:
      - envoy_grpc:
          cluster_name: xds_cluster
  cds_config:
    api_config_source:
      api_type: GRPC
      cluster_names: [xds_cluster]
      grpc_services:
      - envoy_grpc:
          cluster_name: xds_cluster
static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: { seconds: 5 }
    type: STATIC
    hosts:
    - socket_address:
        address: contour.heptio-contour.svc.cluster.local
        port_value: 8001
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9001
```
Which envoy rejects
```
[2018-02-08 00:47:01.269][1][info][main] source/server/server.cc:184] initializing epoch 0 (hot restart version=9.200.16384.127.options=capacity=16384, num_slots=8209 hash=228984379728933363)
[2018-02-08 00:47:01.292][1][critical][main] source/server/server.cc:71] error initializing configuration '/config/contour.yaml': malformed IP address: contour.heptio-contour.svc.cluster.local
```
Figure out if it is possible to use a DNS name for the `xds_cluster` static resource.
