### ISSUE TITLE
No healthy upstreams when service has a single unnamed port that is different than the target port

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#243]
The service in the default kuard setup has a single unnamed port that does not match the target port:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
```

This results in Contour configuring a cluster with an EDS config that specifies serviceName = `default/kuard/80`. On the EDS side, the endpoints have port 8080 instead of 80, so the ClusterLoadAssignments specify a cluster name of `default/kuard/8080`. This mismatch results in Envoy being unable to find any upstreams for the `default/kuard/80` cluster.

This issue goes away by adding a `name` to the port, or by making the service port and the target port equal.
