### ISSUE TITLE
Properly handle service document with one unnamed port targeting a named targetport.

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#247]
The following svc spec
```
spec:
  clusterIP: 10.51.241.155
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32408
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: httpbin
  sessionAffinity: None
  type: NodePort
```
Generates the following endpoint
```
subsets:
- addresses:
  - ip: 10.48.0.94
    nodeName: gke-gke-default-pool-f9137f8c-r4k1
    targetRef:
      kind: Pod
      name: httpbin-5b987fccb5-jms6b
      namespace: default
      resourceVersion: "4062497"
      uid: 12230edc-1520-11e8-94fe-42010a98000d
  ports:
  - port: 8080
    protocol: TCP
```
Which contour mishandles because the cluster.service_name field generated by CDS will be "default/httpbin/http", however there is no named port in the endpoint document. The endpoint controller has done it's job and dereferenced `http` to port 8080 in the container spec, but has not recorded a name in the endpoint document for the port because there is no name in the service spec.

What contour will have to do is, _always_ generate a name for the service port, and never use targetport. Then when EDS is consulting the endpoint document, if there are _no_ named ports, then that the services that reference this port are also unnamed, so rather than using "default/httpbin/8080", use a commonly known identifier. I suggest `default`.

The logic will have to be

CDS: iff there is one service port in the service spec, and it is unnamed, return the name `default`.
EDS: iff there are no ports with a name in the endpoint doc, use the name `default` for the endpoint, and assign all ports in the document to it.

/cc @alexbrand
