### ISSUE TITLE
ingress.kubernetes.io/force-ssl-redirect: "true" forces SSL for all ingresses to domain

### ISSUE THREAD

**Issue by wmedlar** [heptio/contour#250]
This causes issues with cert-manager's ACME HTTP validation, which can be configured to use a separate ingress resource for the challenge. The setup looks something like the following:

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  annotations:
    kubernetes.io/ingress.class: contour
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts: ["example.com"]
      secretName: example-tls
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: app-service
              servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: challenge
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /.well-known/acme-challenge/gVJl5NWL2owUqZekjHkt_bo3OHYC2XNDURRRgLI5JTk
            backend:
              serviceName: challenge-service
              servicePort: 8089
```

The app ingress should always force HTTPS while the challenge ingress should be HTTP-only, however this is not the case and every HTTP request to `example.com`, regardless of the path, is redirected to HTTPS.
