### ISSUE TITLE
Proxying doesn't work for services with different port and targetPort

### ISSUE THREAD

**Issue by Lookyan** [heptio/contour#299]
I found interesting problem. When we have kubernetes service like this:

```
apiVersion: v1
kind: Service
metadata:
  name: ...
  labels:
    service: ...
    app: service
spec:
  type: ClusterIP
  ports:
    - port: 8890
      targetPort: 8888
  selector:
    service: ...
    app: service
```

Then it doesn't work because, as far as I understand, envoy tries to proxy to the port 8890, but endpoint listens 8888 port. So, we get an answer from envoy, that this service doesn't have healthy endpoints.
