### ISSUE TITLE
contour.heptio.com/request-timeout does not appear to work for uploads.

### ISSUE THREAD

**Issue by rimusz** [heptio/contour#318]
where the https://github.com/heptio/contour/blob/master/docs/annotations.md#contour-specific-ingress-annotations should be set, in each ingress or contour deployment? 

and btw thanks for the `contour`, really awesome product, it works very well together with `cert-manager` 👍

**Comment by davecheney** [comment]
Ingress annotations go on the ingress object.

**Comment by davecheney** [comment]
Closing, answered.

**Comment by rimusz** [comment]
hmm, thought that too, but still getting timeouts

**Comment by davecheney** [comment]
Can you give me some more information? What annotations are you using? Can you attach the ingress and service documents you applied.

**Comment by rimusz** [comment]
Copied from my helm chart, app's service:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: app1
    port: 8069
    targetPort: 8069
  selector:
    app: {{ template "fullname" . }}
```
apps' ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "contour"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    contour.heptio.com/request-timeout: "15m"
spec:
  rules:
{{- if .Values.domain.www }}
  - host: www.{{ .Values.domain.host }}
{{- else }}
  - host: {{ .Values.domain.host }}
{{- end }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 8069
  tls:
    - hosts:
      {{- if .Values.domain.www }}
        - www.{{ .Values.domain.host }}
      {{- else }}
        - {{ .Values.domain.host }}
      {{- end }}
      secretName: {{ template "fullname" . }}-tls
```
