### ISSUE TITLE
Add sticky session annotation

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#361]
At the moment the `lb_strategy` for each cluster defaults to whatever Envoy chooses. We should make this configurable via an annotation on the ingress object. Specifically i've been asked if we can support sticky session load balancing.

- [ ] choose an annotation name; `contour.heptio.com/lb-strategy:` sounds good.
- [ ] decide if it applies to the whole vhost, or only the routes mentioned in the ingress, hence you can have several ingresses with the same vhost and alter the lb strategy on a per path basis.

**Comment by rosskukulinski** [comment]
We should probably add this feature off the IngressRoute design instead.  Related to #289 which some  websocket-related libraries need sticky-sessions.  Moving outside 0.6.0 as non-essential to closing out IngressRoute support.

**Comment by davecheney** [comment]
I hoped that we could hide this in a load balancing strategy option. I
haven't looked to see if there is one natively supported by envoy.

**Comment by alexbrand** [comment]
I did some initial research around this when looking into the websockets issue (#595). Found this which seems to indicate that it indeed is handled via a load balancing strategy, more specifically, a "hashing load balancer": https://groups.google.com/d/msg/envoy-users/POeaHFJI2W4/EaciXkZYBgAJ.

**Comment by kidlj** [comment]
In my understanding, and as the ring hash document says, 
> A consistent hashing load balancer is only effective when protocol routing is used that specifies a value to hash on.

So ring hash(load_balancing) and route hash value(hash_policy) work together to achieve sticky session.

In short, I want sticky session.

Here's a example config that should work:

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 12060 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: csr
                  hash_policy:
                    cookie:
                      name: csr_id
                      ttl: 300
          http_filters:
          - name: envoy.router
  clusters:
  - name: csr
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: RING_HASH
    hosts:
    - socket_address: { address: <my_ip>, port_value: 6001 }
    - socket_address: { address: <my_ip>, port_value: 7001 }
    - socket_address: { address: <my_ip>, port_value: 8001 }
```

**Comment by Starblade42** [comment]
I'd love some feedback on how to implement this feature, and want to make sure that I'm heading the right direction in how we'd specify this type of configuration.
(https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-routeaction)
(https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html?highlight=hash_policy#route-routeaction-hashpolicy)

It seems like specifying this on a per-k8s-service basis is correct since they map directly to a cluster, and we declare the lb-strategy on a per-k8s-service basis as well.

This is an example IngressRoute declaring the above Envoy configuration by @kidlj with sticky sessions for `stickysessions.bar.com` on envoy `v1.8.0+`

```
# stickysessions.ingressroute.yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: stickysessions
  namespace: default
spec:
  virtualhost:
    fqdn: stickysessions.bar.com
  routes:
    - match: /service/1
      services:
        - name: service1
          port: 80
          strategy: RingHash
          hashPolicy:
            - connectionProperties:
                sourceIp: true
    - match: /service/2
      services:
        - name: service2
          port: 80
          strategy: RingHash
          hashPolicy:
            - cookie:
                name: envoy-cookie
                ttl: 60s
```

Since the different hash policies can all be specified for a given cluster as a list of policies for Envoy, this means that this is valid envoy and contour configuration:
```
# stickysessions.ingressroute.yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: stickysessions-all-hash-policies
  namespace: default
spec:
  virtualhost:
    fqdn: allhashpolicies.bar.com
  routes:
    - match: /
      services:
        - name: stickeysessionapp
          port: 80
          strategy: RingHash
          hashPolicy:
            - connectionProperties:
                sourceIp: true
              terminal: true
            - cookie:
                name: envoy-cookie
                ttl: 0s
                path: cookie/path
              terminal: true
            - header:
                headerName: userSessionHeader
              terminal: true
```

**Comment by kidlj** [comment]
@Starblade42 Me have the same draft design personally. And the IngressRoute level default load balancing strategy could also be `ring_hash`, then a hash_policy should be specified there.

**Comment by phylake** [comment]
The [protobuf definition](https://github.com/envoyproxy/envoy/blob/v1.9.0/api/envoy/api/v2/route/route.proto#L720-L731) and [docs](https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/route/route.proto#route-routeaction-hashpolicy) already define the structure that should be mirrored here. Hash policy isn't a list of hash policies. The following is more appropriate

```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: stickysessions-all-hash-policies
  namespace: default
spec:
  virtualhost: 
    fqdn: allhashpolicies.bar.com
  routes:
  - match: /
    services:
    - hashPolicy:
        # Precisely one of header, cookie, connection_properties must be set.
        connectionProperties:
          sourceIp: true
        # Precisely one of header, cookie, connection_properties must be set.
        cookie:
          name: envoy-cookie
          path: cookie/path
          ttl: 0s
        terminal: true
        # Precisely one of header, cookie, connection_properties must be set.
        header:
          headerName: userSessionHeader
        # look at the protobuf
        terminal: true
      name: stickeysessionapp
      port: 80
      strategy: RingHash
```

I'm working on this today. Please let me know if the above structure is acceptable.

**Comment by phylake** [comment]
Nope that won't work. HashPolicy is on the [RouteAction](https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/route/route.proto#route-routeaction-hashpolicy), not the Cluster

Also I misread the RouteAction from my previous comment. HashPolicy _is_ a list.

I added a QUESTION inline below
```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: stickysessions-all-hash-policies
  namespace: default
spec:
  virtualhost: 
    fqdn: allhashpolicies.bar.com
  routes:
  - match: /
    # QUESTION: should this be nested under a "route" key as in https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/route/route.proto#route-route ?
    hashPolicy:
    - connectionProperties:
        sourceIp: true
      # Precisely one of header, cookie, connection_properties must be set.
      cookie:
        name: envoy-cookie
        path: cookie/path
        ttl: 0s
      # Precisely one of header, cookie, connection_properties must be set.
      header:
        headerName: userSessionHeader
      # look at the protobuf
      terminal: true
    services:
    - name: stickeysessionapp
      port: 80
      strategy: RingHash
```
