### ISSUE TITLE
master contour routing and TLS versions

### ISSUE THREAD

**Issue by robertlemmen** [heptio/contour#394]
by accident I had the "master" contour in my system, rather than "latest". so your recent commits did get some extra testing in a real system, yeah! 

We did experience an issue with this issue of contour, it somehow made the corresponding envoy talk to the backing esp in a way that used TLS, but the backing esp never does speak TLS. 

```
[2018-05-15 13:05:16.934][14][debug][connection] source/common/ssl/ssl_socket.cc:138] [C4] SSL error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

Sorry I do not have any more details and logs, but perhaps it's useful as a test case anyway....

**Comment by davecheney** [comment]
@robertlemmen thanks for raising this issue. I'm going to need a few more details before I can properly debug this one. From what you've told me so far it looks like the backend Service talks TLS but Envoy tried to talk to it via plain HTTP.

- [ ] Can you please attach a copy of your `Ingress` and `Service` documents.
- [ ] Does this problem only occur with `:master`?

**Comment by davecheney** [comment]
@robertlemmen gentle ping

**Comment by robertlemmen** [comment]
as of a few days ago, the problem also happens with latest, simply because that moved ahead. btw, we were kinda expecting latest to point to releases, so e.g. v0.5.0 at the moment, and were a bit surprised when the alpha release got distributed as latest...

my ingress controller basically looks like this:
```
    spec:
      containers:
      - args:
        - -c
        - /config/contour.yaml
        - --service-cluster
        - cluster0
        - --service-node
        - node0
        - -l
        - info
        - --v2-config-only
        command:
        - envoy
        image: docker.io/envoyproxy/envoy-alpine:v1.6.0
        imagePullPolicy: IfNotPresent
        name: envoy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: contour-config
      - args:
        - serve
        - --incluster
        - --ingress-class-name
        - contour-mg
        command:
        - contour
        image: gcr.io/heptio-images/contour:latest
        imagePullPolicy: Always
        name: contour
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - bootstrap
        - /config/contour.yaml
        command:
        - contour
        image: gcr.io/heptio-images/contour:latest
        imagePullPolicy: Always
        name: envoy-initconfig
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: contour-config
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: contour-config
```

and the service that it talks to:
```
   spec:
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: *******
        image: ********
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/liveness
            port: 50052
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: master
        ports:
        - containerPort: 50051
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/readiness
            port: 50052
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: ***********
          name: google-credentials
          readOnly: true
        - mountPath: **********
          name: config-volume
          readOnly: true
      - args:
        - --http2_port
        - "8081"
        - --backend
        - grpc://127.0.0.1:50051
        - --service
        - **********************
        - --version
        - 2018-04-16r0
        image: gcr.io/endpoints-release/endpoints-runtime:1
        imagePullPolicy: Always
        name: esp
        ports:
        - containerPort: 8081
          name: external-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
```
downgrading contour to v0.5.0 seems to avoid the problem. note that the problematic requests never arrive at our actual service, it's teh communication between envoy and the esp that is the problem

thanks for looking, let me know if you need anymore information
