### ISSUE TITLE
Add handling for a default TLS certificate

### ISSUE THREAD

**Issue by mattalberts** [heptio/contour#410]
### Feature Request: Add handling for a default TLS certificate
 * Search Terms: "is:issue is:open TLS"

Add handling to allow use of a default TLS certificate, following these guidelines
 * The certificate is specified as a ```<namespace>/<name>``` reference to a secret.
 * The default secret is applied to Ingress specs that specify tls without providing spec.tls.secretName
 * Existing matching rules against spec.tls.hosts are still satisfied.
 * An Ingress spec.tls.secretName overrides the default secret.
 * The default secret does not apply to the default host "*"

Hopefully the guidelines don't sound to dogmatic. 😄  

All I'm try to capture is a loosening of ```validTLSSpecforVhost``` to only reject a TLS spec if both the default secret and  ```spec.tls.secretName``` are not set.
 * https://github.com/heptio/contour/blob/master/internal/contour/virtualhost.go#L234-L237

#### Example Depolyment|Container Definition
```yaml
        - name: contour
          image: gcr.io/heptio-images/contour:latest
          imagePullPolicy: Always
          command: ["contour"]
          args:
            - serve
            - --incluster
            - --ingress-class-name=contour
            - --default-tls-secret=$(POD_NAMESPACE)/contour-ingress
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

#### Example Ingress Definition
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: contour-echo
  labels:
    ingress: contour
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  tls:
  - hosts:
    - echo.127.0.0.1.xip.io
  rules:
  - host: echo.127.0.0.1.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80
---
```
> * we specify tls with a host but leave the secretName empty to use the default secret.
> * the behavior is similar to both the nginx and haproxy ingress controllers.
