### ISSUE TITLE
ingressroute needs support for kubernetes.io/ingress.allow-http: false

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#455]
Ingressroute needs support for the equiv. of Ingresses `kubernetes.io/ingress.allow-http: false`

This should be a property on the spec.virtualhost object, it cannot be specified on a delegate. 
```
spec:
  virtualhost:
     fqdn: "example.com"
     allow-http: false
```
Allow-http defaults to true.

Needs internal/dag and internal/e2e tests to verify that allow-http: false prevents generation of `ingress_http` routes and vhost entries.
