### ISSUE TITLE
internal/dag: default path to "/" when Match field of IngressRoute is empty

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#463]
When processing Ingress resources, we set the dag.Route's path to `/` when the path on the IngressRule is empty.

We should do the same when processing IngressRoute resources. That is, set the `path` field of the dag.Route struct to `/` when the `Match` field of an IngressRoute is empty.

**Comment by davecheney** [comment]
I don't think we should do this; this is a small concession to avoid writing one line and ads confusion --we have to document what prefix is assumed when no match is supplied. Then we also need to specify what happens in this case
```
spec:
  virtualhost: ...
  routes:
  - services:
     - name: foo
        port: 9000
  - services: 
     - name: bar
        port: 9001
```
I think we should make the `match:` field mandatory.
