### ISSUE TITLE
ingressroute: add CORS support

### ISSUE THREAD

**Issue by glerchundi** [heptio/contour#465]
Feature request to add CORS support in `IngressRoute`. Envoy already supports this at ~route~ virtual host level so it seems to be plausible to add it on the `virtualhost` section, something like:

```
[...]
    tls:
      # required, the name of a secret in the current namespace
      secretName: google-tls
      # other properties like cipher suites may be added later
    # if present describes the CORS policy.
    cors:
      # Specifies the origins that will be allowed to do CORS requests.
      allowOrigin:
        - www.google.com
        - google.com
      # Specifies the content for the *access-control-allow-methods*
      # header.
      allowMethods:
        - GET
        - POST
      # Specifies the content for the *access-control-allow-headers*
      # header.
      allowHeaders:
        - Content-Type
      # Specifies the content for the *access-control-expose-headers*
      # header.
      exposeHeaders:
        - Content-Type
      # Specifies the content for the *access-control-max-age* header.
      maxAge: 24h
      # Specifies whether the resource allows credentials.
      allowCredentials: true
  strategy: RoundRobin # (Optional) LB Algorithm to apply to all services, defaults for all services
[...]
```

WDYT @davecheney?
