### ISSUE TITLE
IngressRoute weights shouldn't need to add up to 100

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#477]
Currently if the sum of the `weight` values for a set of Services in a Route is not equal to 100, then Envoy will fail to accept the updated configuration from Contour.

```
[2018-06-28 03:32:29.523][1][warning][upstream] source/common/config/grpc_mux_impl.cc:188] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration update rejected: Sum of weights in the weighted_cluster should add up to 100
[2018-06-28 03:32:29.523][1][warning][config] bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:69] gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Sum of weights in the weighted_cluster should add up to 100
```

The IngressRoute design is not defined, but I believe previous discussions concluded that Contour would translate the weights provided by the user into acceptable ratios for envoy.

**Comment by rosskukulinski** [comment]
This is an example of an invalid IngressRoute in the current system
```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: mixed
spec:
  routes:
  - match: /
    services:
    - name: green-kuard
      port: 8080
      weight: 50
  virtualhost:
    fqdn: mixed.dev.kukulinski.com
```

**Comment by rosskukulinski** [comment]
so is this:
```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: mixed
spec:
  routes:
  - match: /
    services:
    - name: green-kuard
      port: 8080
      weight: 1
    - name: green-kuard
      port: 8080
      weight: 1
  virtualhost:
    fqdn: mixed.dev.kukulinski.com
```
