### ISSUE TITLE
Mismatch in the allowed load balancing strategies in the CRD validation spec

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#530]
The following LB strategies are allowed at the default level:

```yaml
            strategy:
              type: string
              enum:
                - RoundRobin
                - WeightedLeastRequest
                - Random
```

but the following are allowed at the service level:

```yaml
                          enum:
                            - RoundRobin
                            - WeightedLeastRequest
                            - Random
                            - RingHash
                            - Maglev
```

These lists should be the same.
