### ISSUE TITLE
Minor syntactical change proposal

### ISSUE THREAD

**Issue by stephenmoloney** [heptio/contour#568]
***Issue:***

A line like this:

```yaml
args: ["-c", "/config/contour.yaml", "--service-cluster", "cluster0", "--service-node", "node0", "-l", "info", "--v2-config-only"]
```

is a bit long for my liking with the potential to be even longer if using amendments.

***Suggestion:***

Syntax changes to break the arguments over multiple lines - example outlined below:

```yaml
       - image: gcr.io/heptio-images/contour:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: contour
        name: contour
        command: ["contour"]
        args:
        - serve
        - --incluster
        - --envoy-http-port=80
        - --envoy-https-port=443
```
I'm happy to make a PR for this proposal....
