### ISSUE TITLE
Support HTTP2 ingress.kubernetes.io/secure-backends: "true"

### ISSUE THREAD

**Issue by andrewwebber** [heptio/contour#569]
I am considering migrating from [https://github.com/zlabjp/nghttpx-ingress-lb](nghttpx-ingress-lb) which has served me well as one of the first http2/grpc ingress controller.

From a security point of view, proxying a secure backend is critical for me as well as controlling HTTP2/HTTP1.1 protocols. 

nghttpx-ingress-lb accomplished this with the following annotations .

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-https
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.zlab.co.jp/backend-config: '{"push": {"8013": {"proto": "http/1.1", "tls": true, "dns": true}}, "gateway": {"443": {"proto": "h2", "tls": true, "dns": true}}}'
```

**Comment by davecheney** [comment]
Thanks for raising this issue. 

> ingress.kubernetes.io/secure-backends: "true"

Did you mean nginx.ingress.kubernetes.io/secure-backends: "true" ? See https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md

For ingress.zlab.co.jp/backend-config:, contour already supports some of the aspects of this as an annotation on the service object, https://github.com/heptio/contour/blob/master/docs/annotations.md#contour-specific-service-annotations

I'm going to mark this as 0.7 to continue the discussion. I'm afraid I won't be able to look at it for the 0.6 cycle.

**Comment by andrewwebber** [comment]
My understanding was that **ingress.kubernetes.io/secure-backends** was not nginx specific but ingress controller agnostics.

A vault operator [example](https://coreos.com/tectonic/docs/latest/vault-operator/user/ingress.html)
```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: vault
  namespace: default
  annotations:
    ingress.kubernetes.io/secure-backends: 'true'
    kubernetes.io/ingress.class: tectonic
spec:
  tls:
    - hosts:
        - vault.ingress.staging.core-os.net
      secretName: vault-server-ingress-tls
  rules:
    - host: vault.ingress.staging.core-os.net
      http:
        paths:
          - path: /
            backend:
              serviceName: example
              servicePort: 8200
```
