### ISSUE TITLE
Root IngressRoutes that define the same FQDN can result in conflicting ingress configuration

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#601]
Currently, it is possible to define multiple root IngressRoutes that specify the same FQDN. Conflict can arise when two (or more) IngressRoutes define the same FQDN + path combination but point the route to a different service. For example:

```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: numberone
spec: 
  virtualhost:
    fqdn: example.com
  routes: 
    - match: /
      services: 
        - name: service1
          port: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: numbertwo
spec: 
  virtualhost:
    fqdn: example.com
  routes: 
    - match: /
      services: 
        - name: service2
          port: 80
```

One potential solution is to enforce that a given FQDN can only be used in a single Root IngressRoute. 

xref: https://github.com/heptio/gimbal/issues/209
