### ISSUE TITLE
Scaling a deployment to zero replicas does not remove endpoints from EDS

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#602]
I think the problem is here: https://github.com/heptio/contour/blob/master/internal/contour/endpointstranslator.go#L72

When scaling a deployment to zero, the Endpoints object has zero subsets, which causes Contour to basically ignore the update.

#### Steps to reproduce:

1. Create a deployment
```
kubectl run nginx --image=nginx --expose --port 80
```

2. Create an ingressroute for the deployment

```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: nginx
spec:
  routes:
  - match: /
    services:
    - name: nginx
      port: 80
  virtualhost:
    fqdn: example.com
```

3. Verify that nginx is accessible via the ingressroute

4. Scale the deployment to zero replicas:
```
kubectl scale deploy nginx --replicas=0
```

Expected result: The cluster is removed from EDS.

Actual result: The cluster remains in the EDS response, and can be verified with `contour cli eds | grep nginx`.
