### ISSUE TITLE
IngressRoute should provide additional printed columns

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#617]
Kuberentes v1.11.0 introduced a [new feature](https://github.com/kubernetes/kubernetes/pull/60991) for CRDs called server server side printing.  Basically this allows you to define additional columns in your CRD that will be output when `kubectl get` is run.

As an example:

```
apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: crontabs.stable.example.com
  spec:
    group: stable.example.com
    version: v1
    scope: Namespaced
    names:
      plural: crontabs
      singular: crontab
      kind: CronTab
      shortNames:
      - ct
    additionalPrinterColumns:
    - name: Spec
      type: string
      description: The cron spec defining the interval a CronJob is run
      JSONPath: .spec.cronSpec
    - name: Replicas
      type: integer
      description: The number of jobs launched by the CronJob
      JSONPath: .spec.replicas
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
```

I think it would be a nice feature to add column outputs for IngressRoute CRDs.
