### ISSUE TITLE
Support HTTP challenges when using annotation force-ssl-redirect: "true"

### ISSUE THREAD

**Issue by stephenmoloney** [heptio/contour#623]
**Describe the absent feature**

When the annotation 
```
ingress.kubernetes.io/force-ssl-redirect: "true"
```
is set, requests are redirected to https as expected.

However, this presents a problem on one particular url, namely,
```
/.well-known/acme-challenge/
```

If using a package like [jetstack cert-manager](https://github.com/jetstack/cert-manager), requests will be made for ACME challenges over HTTP.

Then those requests seem to be redirected by envoy to HTTPS resulting in a failed challenge.

**Potential solutions:**

- `/.well-known/acme-challenge` to be not redirected by default 

or 

- an option as an annotation to add list of exception paths to https redirection

**Anything else you would like to add:**

It seems like there was an issue like this before with other ingress controllers but has since been resolved.

See [this issue from jetstack cert manager](https://github.com/jetstack/cert-manager/issues/194)

Also, in [this related issue](https://github.com/heptio/contour/issues/250), it seems the solution was to create an additional ingress resource. 

**Environment:**

- Contour version: v0.6.0-beta.2, envoy: v1.7.0
- Kubernetes version: v1.11.1
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: baremetal
- OS ubuntu

**Comment by rosskukulinski** [comment]
Also related nginx feature: https://github.com/kubernetes/ingress-nginx/pull/2203

**Comment by davecheney** [comment]
@stephenmoloney can you please verify this with contour 0.6. I think it should work with the following caveats

- routes for vhost described in a single ingress object with `ingress.kubernetes.io/force-ssl-redirect: "true"` on
- cert-managers ingress object exists in its own namespace and lacks `ingress.kubernetes.io/force-ssl-redirect: "true"`

**Comment by stephenmoloney** [comment]
will give you an update soon

**Comment by stephenmoloney** [comment]
Ok, So I finally got to try this today and from what I can tell, requests to `/.well-known/acme-challenge/` are still being redirected.

Example log from envoy when the annotation is `ingress.kubernetes.io/force-ssl-redirect: "true"`
```text
[2018-11-20T15:32:44.266Z] "GET /.well-known/acme-challenge/<redacted_challenge_code> HTTP/1.1" 301 - 0 0 0 - "<redacted_ip>" "Go-http-client/1.1" "332fb142-6a6d-4324-902d-92683be59170" "<redacted_domain>" "-
```

Example log from envoy when the annotation is 
```text
[2018-11-20T16:09:04.034Z] "GET /.well-known/acme-challenge/<redacted_code> HTTP/1.1" 200 - 0 113 0 0 "<redacted_ip>" "Go-http-client/1.1" "dd496c95-9767-4440-bec6-5d4b642a9fdc" "<redacted_domain>" "<redacted_ip>"
[2018-11-20 16:09:08.847][1][info][upstream] source/common/upstream/cluster_manager_impl.cc:442] removing cluster <namespace>/cm-acme-http-solver-6vrcb/8089/da39a3ee5e
[2018-11-20 16:09:10.895][1][info][upstream] source/server/lds_api.cc:73] lds: add/update listener 'ingress_https'
[2018-11-20T16:09:07.522Z] "GET /.well-known/acme-challenge/<redacted_code> HTTP/1.1" 200 - 0 113 1 1 "<redacted_ip>" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "274bd474-96ae-4544-a2ca-79f7868ca607" "<redacted_domain>" ""
```

The ingress object is of type `extensions/v1beta1` and looks something like this:

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-saleor
  labels:
    app: saleor
    chart: saleor-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    certmanager.k8s.io/cluster-issuer: default-issuer
    contour.heptio.com/num-retries: "3"
    contour.heptio.com/request-timeout: 30s
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
    
spec:
  tls:
    - hosts:
        - <redacted_domain>
      secretName: ssl-certificate-private-key
  rules:
    - host:  <redacted_domain>
      http:
        paths:
          - path: /media/
            backend:
              serviceName: RELEASE-NAME-saleor-nginx
              servicePort: http-nginx
          - path: /static/
            backend:
              serviceName: RELEASE-NAME-saleor-nginx
              servicePort: http-nginx
          - path: /
            backend:
              serviceName: RELEASE-NAME-saleor-django
              servicePort: http-django
```

A cluster issuer is being used by cert-manager.


Versions:
contour: 0.7.0
cert-manager: 0.5.2
