### ISSUE TITLE
ingressroute: drop spec.virtualhost.aliases

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#625]
When we designed the ingressroute spec[0] I made a case that the virtualhost spec should have an explicit place to place aliases. The idea was to explicitly support configurations like this
```
spec:
  virtualhost:
    fqdn: www.heptio.com
    aliases:
      - heptio.com
      - hept.io
```
However, this design introduces several areas of ambiguity, namely:

1. The `spec.virtualhost.fqdn` field is the _key_ (essentially) for the root of this ingress's graph of routes. However when checking for conflicts the concatenation of spec.virtualhost.fqdn and .aliases must be consulted -- this is tricky because if we forget a spot, bugs leak in.
2. Aliases are by the definition not the key of the virtualhost; so if I or someone else creates a virtualhost with an fqdn listed in another's alias list, is that an error?
3. If an aliases is mentioned in two alias lists, is that an error, even if the fqdn's are different?

These are lots of edge cases that take time to debate for relatively little benefit as my initial design for the use case for aliases was lacking. 

The reason a user wants to group a set of domain names together into an associated lump is because they are related, however for good SEO they should not serve the same content -- search engines finding the same content on three distinct domains (www and non www are considered distinct) will pick one as authoritative and penalise the others as copy cats. 

I think in 0.7 we should drop the aliases field. The use case behind his feature can be simulated with the following somewhat forward looking syntax:
```
spec:
  virtualhost:
    fqdn: www.heptio.com
  routes:
    - match: /
      services: 
        - name: s1
           port: 80
---
spec:
  virtualhost:
    fqdn: heptio.com
  routes:
    - match: /
      redirect: www.heptio.com
```
Which will 301 requests to `heptio.com` back to `www.heptio.com`, and
```
meta:
  name: www_heptio_com
spec:
  virtualhost:
    fqdn: www.heptio.com
  routes:
    - match: /
      delegate:
        - name: heptio
---
meta:
  name: heptio_com
spec:
  virtualhost:
    fqdn: heptio.com
  routes:
    - match: /
      delegate:
        - name: heptio
---
meta:
  name: heptio
spec:
  routes:
    - match: /
       service:
        - name: s1
           port: 80     
```
which will serve the delegate ingressroute `heptio` on both `www.heptio.com` and `heptio.com`

[0]: https://github.com/heptio/contour/blob/master/docs/ingressroute.md
