### ISSUE TITLE
v0.6.0:  envoy fails to listen on 0.0.0.0:8443 ?

### ISSUE THREAD

**Issue by jcrowthe** [heptio/contour#694]
**What steps did you take and what happened:**
1. `kubectl apply` this file: https://github.com/heptio/contour/blob/master/deployment/render/daemonset-rbac.yaml
2. `netstat -antp` inside envoy container:
```
$ k exec -it contour-fbv2k ash -nheptio-contour
Defaulting container name to contour.
Use 'kubectl describe pod/contour-fbv2k -n heptio-contour' to see all of the containers in this pod.
/ # netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      1/contour
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      1/contour
tcp        0      0 127.0.0.1:50522         127.0.0.1:8001          ESTABLISHED -
tcp        0      0 172.16.7.170:58934      192.168.0.1:443         ESTABLISHED 1/contour
tcp        0      0 127.0.0.1:8001          127.0.0.1:50522         ESTABLISHED 1/contour
tcp        0      0 :::8000                 :::*                    LISTEN      1/contour
/ #
```

The k8s service yaml specifies the envoy container should be [listening on 8443](https://github.com/heptio/contour/blob/master/deployment/render/daemonset-rbac.yaml#L306) but I am not seeing that happen starting with v0.6.0.

Honestly this is really sketchy to me but I can't find any reason why my cluster would specifically be having an issue. When I deploy v0.5.0 I have no issues, whereas with v0.6.0 Contour fails to respond to traffic coming in publicly on 443, due to envoy not listening on :8443.

 Am I just crazy? Can anyone reproduce this issue?

**What did you expect to happen:**
Envoy container should be listening on 0.0.0.0:8443

**Environment:**

- Contour version: v0.6.0
- Kubernetes version: v1.11.2
- Kubernetes installer & version: Custom
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): CoreOS

**Comment by davecheney** [comment]
Hi @jcrowthe contour will only create an envoy listener for port :8443 if there is at least one ingress with a matching secret.

Could you try grabbing the /config output from the admin interface on an envoy container, https://github.com/heptio/contour/blob/master/docs/troubleshooting.md#access-the-envoy-admin-interface-remotely. Be aware that /config includes TLS keys and secrets so please anonymise them if this is not a throwaway certiface.

**Comment by jcrowthe** [comment]
Ah, interesting. I've found the issue, and it is due to a lack of strong input validation in k8s (maybe for backwards compatibility?).

I had TLS specified in the ingress definition, but only as the following:
```
  tls:
  - secretName: my-cert
```
rather than
```
  tls:
  - secretName: my-cert
    hosts:
    - canary.example.net
```
Interestingly, this is accepted by k8s, but does not trigger contour/envoy to load 443 (80 loads fine). But it doesn't stop there, just playing around with the input (googling for random ingress definitions with TLS), there appear to be more configurations that are accepted by k8s but are not read in by contour/envoy for port 443.

No worries, I'll chalk this up to user error in this case. But if you wanted to do something, maybe reference the proper config format on the [tls.md](https://github.com/heptio/contour/blob/master/docs/tls.md)? (also that doc has a dead link) Anyway, for future reference of other users:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary
  namespace: my-namespace
spec:
  rules:
  - host: canary.example.net
    http:
      paths:
      - backend:
          serviceName: canary
          servicePort: 80
        path: /
  tls:
  - secretName: my-cert
    hosts:
    - canary.example.net
status:
  loadBalancer: {}
```
