### ISSUE TITLE
Healthcheck Envoy

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#695]
**Describe the solution you'd like**

Allow the ability to health check Envoy by using the health check filter (https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/health_check/v2/health_check.proto#envoy-api-msg-config-filter-http-health-check-v2-healthcheck). 

**Anything else you would like to add:**

Updating the config passed to Envoy we could add this to the stats listener (or could add a new listener, but was trying to avoid having too many) which enables the health check filter on Envoy itself:

```
http_filters:
  - name: envoy.health_check
                     config:
                        endpoint: "/healthz"
                        pass_through_mode: false
```

Once implemented curling will return a 200 or 503:
```sh
$ curl -i  http://localhost:8002/healthz                                                                     
HTTP/1.1 200 OK
x-envoy-upstream-healthchecked-cluster: cluster0
date: Fri, 21 Sep 2018 02:37:25 GMT
server: envoy
content-length: 0
---
$  curl -i  http://localhost:8002/healthz                                                                     
HTTP/1.1 503 Service Unavailable
x-envoy-upstream-healthchecked-cluster: cluster0
date: Fri, 21 Sep 2018 02:48:57 GMT
server: envoy
content-length: 0
```

// cc @rdrgmnzs
