### ISSUE TITLE
gRPC example

### ISSUE THREAD

**Issue by GoingFast** [heptio/contour#765]
I'd really like a simple helloworld gRPC example. Everything else is working but I cant figure out how to implement gRPC

**Comment by davecheney** [comment]
I'm sorry i misunderstood your request.

Can you please list precisely what you are trying to do, what you have tried, and what happened when you tried. If you can include code, that would be very beneficial to be able to understand where you are stuck.

**Comment by rochacon** [comment]
Hey @GoingFast, I think what you're looking for is the `contour.heptio.com/upstream-protocol.h2` [Contour `Service` annotation](https://github.com/heptio/contour/blob/v0.6.1/docs/annotations.md#contour-specific-service-annotations). Try setting this up in your gRPC `Service` manifest with the port number/name the server is bind to as the annotation value.

**Comment by GoingFast** [comment]
Yes I got it working thanks. Problem wasn't in Contour but my spec rules. I'm still fairly new to k8s so I'm not really sure if the setup I have currently is ok.
```
spec:
  rules:
    - host:
      http:
        paths:
          - path: /hello
            backend:
              serviceName: hello-server
              servicePort: grpc
```
and I dial `hello-server.default.svc.cluster.local:50051`. I write the hostnames and it seems to be working.
