### ISSUE TITLE
IngressRoute not work if configure Contour as NodePort type service

### ISSUE THREAD

**Issue by fkpwolf** [heptio/contour#814]
**What steps did you take and what happened:**
I install k8s by kubeadm and there is no LoadBalance stuff like aws ELB. So I modify contour as NodePort service. But for IngressRoute I find I can't access by either hostname:port or hostname. Can I change value of fqdn to * so I can access by ip?

```
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: kuard
  namespace: default
spec:
  virtualhost:
    fqdn: contour.192.168.51.11.nip.io
  routes:
    - match: /
      services:
        - name: kuard
          port: 80
    - match: /service2
      prefixRewrite: "/" # Setting this rewrites the request from `/service2` to `/`
      services:
        - name: kuard
          port: 80

```

**What did you expect to happen:**
I can access kuard page.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Contour version:
- Kubernetes version: (use `kubectl version`): v1.11.2
- Kubernetes installer & version: kubeadm
- Cloud provider or hardware configuration: kubeadm
- OS (e.g. from `/etc/os-release`): Centos 7
