### ISSUE TITLE
Support of external endpoints as targets for proxying

### ISSUE THREAD

**Issue by anapsix** [heptio/contour#825]
**Describe the solution you'd like**
Would love to be able to define `Ingress` and/or `IngressRoute` objects, that would allow specifying endpoints outside of k8s cluster as targets for proxying.
Unlike #334, this feature would not rely on Service object, and would achieve described functionality directly.

Manifest could look like this, for example:
```
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: weight-shifting
  namespace: default
spec:
  virtualhost:
    fqdn: weights.bar.com
  routes:
    - match: /
      hosts:
        - name: s1
          host: s1.bar.com
          port: 80
          weight: 10
        - name: s2
          host: s2.bar.com
          port: 80
          weight: 90
```
