### ISSUE TITLE
Delegate IngressRoute can also "look" like a root ingressroute

### ISSUE THREAD

**Issue by stevesloka** [heptio/contour#865]
**Describe the solution you'd like**
Currently, if I have an IngressRoute that delegates to another, it's possible that the delegated IngressRoute also references a virtualhost even though that virtualhost will be ignored. 

Nothing that the DAG builds seems to be affected by this, just looks incorrect and seems like we should throw a status error stating that you can't define virtual hosts for any delegate. 

Example: 
```
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: root-blog
  namespace: root-ingressroute
spec: 
  virtualhost:
    fqdn: blog.containersteve.com
    tls:
      secretName: blog-containersteve-com
  routes: 
    - match: /
      delegate:
        name: blog
        namespace: marketing
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: blog
  namespace: marketing
spec: 
  virtualhost:
    fqdn: blog.containersteve.com
    tls:
      secretName: blog-containersteve-com
  routes: 
    - match: /
      services: 
      - name: green
        port: 80  
```
