### ISSUE TITLE
Add readinessProbe to deployment examples

### ISSUE THREAD

**Issue by davecheney** [heptio/contour#87]
```
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
```

Something like this, requires #10
