### ISSUE TITLE
TLS Passthrough & HTTP Redirect

### ISSUE THREAD

**Issue by 256dpi** [heptio/contour#910]
I have a pod that accepts only HTTPS traffic on port 443. To route the traffic, I used an IngressRoute with the new TLS Passthrough option:

```yml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: test
spec:
  virtualhost:
    fqdn: test.example.com
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: test
        port: 443
  routes:
    - match: /
      services:
        - name: test
          port: 443
```

The TLS forwarding works great. However, contour is not accepting traffic on port 80 and therefore does not auto-redirect the request to the HTTPS port. Am I missing some configuration?

**Environment:**

- Contour version: 0.9.0
- Kubernetes version: 1.11 (kubectl: 1.13)
- Cloud provider or hardware configuration: GKE

**Comment by davecheney** [comment]
Thank you for your issue. The problem is when using tcpproxy you're mixing L4 and L7 in this service. I see the argument that for your service you want to provide HTTPS from the backend service using TCP forwarding, so it makes sense that you'd want to have a 80 -> 443 redirect. But that is only in the case where your backend service is HTTPS, if it were some other service using TLS as a transport, then port 80 redirection does not make sense.

**Comment by 256dpi** [comment]
@davecheney  Thanks for the detailed explanation!

It would be nice if contour would support that out of the box in a HTTPS forwarding scenario.

I'm now trying to forward the HTTP traffic to my instance and perform the redirect there using this config:

```yml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: test
spec:
  virtualhost:
    fqdn: test.example.com
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: test
        port: 443
  routes:
    - match: /
      services:
        - name: test
          port: 80
          permitInsecure: true
```

Unfortunately, It's not working. Is this the right approach? Do I need two separate ingress route definitions? Thanks for your help!
