### ISSUE TITLE
Endpoints are missing for Contour when installed on an IPV6 only kubernetes cluster

### ISSUE THREAD

**Issue by roshnihp** [heptio/contour#911]
**What steps did you take and what happened:**
1. I have an IPV6 only kubernetes cluster with one master and one worker node. 
2. Installed Contour using 'kubectl apply -f https://j.hept.io/contour-deployment-rbac'
3. I can see Contour pods are running with IPV6 addresses. I can also list service which has IPV6 address.
4. When I list endpoints using 'kubectl get endpoints --all-namespaces' , contour has empty field while all other services got endpoints.

**What did you expect to happen:**
Contour should be able to detect the endpoints , the same way as in IPV4 cluster.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Not sure whether anything need to be set in Contour for IPV6 support. If yes then the documentation needs to include those details.

**Environment:**

- Contour version: master
- Kubernetes version: (use `kubectl version`): 1. 13.3
- Kubernetes installer & version: kubeadm 1.13.3
- Cloud provider or hardware configuration: k8s on VMs 
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 LTS

**Comment by davecheney** [comment]
Thank you for raising this bug. Can you please clarify for me which service is missing an endpoint?

Can you please show the output of

`kubectl get endpoints -n heptio-contour contour`

**Comment by roshnihp** [comment]
Here is the output
root@master1:/home/roshini# kubectl get endpoints -n heptio-contour contour
NAME      ENDPOINTS   AGE
contour               32s

The service and pods are created  as below 
root@master1:/home/roshini# kubectl get svc -n heptio-contour
NAME      TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
contour   LoadBalancer   2019::a00:2a44   <pending>     80:32557/TCP,443:32496/TCP   21s

root@master1:/home/roshini# kubectl get pods -n heptio-contour -o wide
NAME                      READY   STATUS    RESTARTS   AGE    IP                 NODE      NOMINATED NODE   READINESS GATES
contour-d9b58c698-99jw4   1/2     Running   0          2m6s   2019::1:c0a8:132   worker1   <none>           <none>
contour-d9b58c698-ngjvh   1/2     Running   0          2m6s   2019::1:c0a8:131   worker1   <none>           <none>

**Comment by davecheney** [comment]
@roshnihp thank you for your reply. I can see from that output that there are endpoint objects for the contour service. Does this answer point 4 of your original question?

**Comment by roshnihp** [comment]
No, As you can see the ENDPOINTS field is empty . As the Contour pods are running it should be listed as part of endpoints like for other services below.
root@master1:/home/roshini# kubectl get endpoints
NAME            ENDPOINTS                                                                       AGE
kubernetes      [2019::100]:6443                                                                4h46m
nginx-service   [2019::1:c0a8:12d]:80,[2019::1:c0a8:12e]:80,[2019::1:c0a8:12f]:80 + 1 more...   4h42m

**Comment by davecheney** [comment]
I am sorry, you are correct.

I'm afraid this is outside what I can assist you with, this not a contour issue, the endpoints object is maintained by kubernetes itself and the problem is likely with your kubernetes cluster. I'll ping a few people on our field engineering team who may have some suggestions.

**Comment by roshnihp** [comment]
It worked on IPV4 cluster and can see endpoints populated.
I have asked my colleagues to try it on their IPV6 cluster and the result is same.
Is there any setting that we need to apply in https://j.hept.io/contour-deployment-rbac to make it work in IPV6 cluster?

**Comment by davecheney** [comment]
Try setting `clusterIP: None` on the contour service, and removing `type: LoadBalancer`

**Comment by uablrek** [comment]
If you try `netstat` inside the cntour pod it looks like only ipv4 ports are open;
```
kubectl exec -it contour-788bb8fd5c-8jbb6 -c envoy sh
# netstat -putan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      1/envoy
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      1/envoy
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:56930         127.0.0.1:8001          ESTABLISHED 1/envoy
tcp        0      0 127.0.0.1:8001          127.0.0.1:56930         ESTABLISHED -
tcp        0      0 :::8000                 :::*                    LISTEN      -
tcp        0      0 1000::2:b00:402:54364   fd00:4000::1:443        ESTABLISHED -
```

**Comment by roshnihp** [comment]
Is this something related to settings like mentioned in this issue https://github.com/heptio/contour/issues/895 ?

I have tried ClusterIP None and no endpoints populated and cannot ping. 
As mentioned by @uablrek I have tried netstat -putan in one of the pod and cannot see 8080 opened.

However I tried to check the same in an **IPV4** cluster and I can see 8080 is opened as below
```
root@master1:/home/roshini# kubectl exec -ti contour-889657c8f-p5gmc /bin/sh -n heptio-contour
Defaulting container name to contour.
Use 'kubectl describe pod/contour-889657c8f-p5gmc -n heptio-contour' to see all of the containers in this pod.
```
```
/ # netstat -putan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      1/contour
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      1/contour
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
```

**Comment by alexbrand** [comment]
Hey @roshnihp, can you try setting the `--xds-address` flag to `::1` in the `args` of the contour container? This is what the `args` field would look like in the Deployment contained within https://j.hept.io/contour-deployment-rbac

```
containers:
      - image: gcr.io/heptio-images/contour:master
        imagePullPolicy: Always
        name: contour
        command: ["contour"]
        args: ["serve", "--incluster", "--xds-address", "::1"]
```

**Comment by roshnihp** [comment]
The output looks as below in the container.
```
/ # netstat -putan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      1/contour
tcp        0      0 :::8000                 :::*                    LISTEN      1/contour
tcp        0      0 ::1:8001                :::*                    LISTEN      1/contour
```
 I can see  0 ::1:8001 opened. However 8080 is missing and hence no endpoints populated. Is there any similar setting that can be done to open 8080 ?

**Comment by alexbrand** [comment]
Great, looks like Contour is correctly serving on `::1`. 

We need to tell Envoy to use `::1` to talk to Contour. We can do this by modifying the init container that configures Envoy:
```
      initContainers:
      - image: gcr.io/heptio-images/contour:master
        imagePullPolicy: Always
        name: envoy-initconfig
        command: ["contour"]
        args:
        - bootstrap
        - xds-address="::1"
        # Uncomment the statsd-enable to enable statsd metrics
        #- --statsd-enable
        # Uncomment to set a custom stats emission address and port
        #- --stats-address=0.0.0.0
        #- --stats-port=8002
        - /config/contour.json
```

We also need to tell Envoy to listen on `::` (all IPv6 interfaces) for requests. We can do this by passing the `envoy-service-http-address` and `envoy-service-https-address` flags to Contour:

```
     containers:
      - image: gcr.io/heptio-images/contour:master
        imagePullPolicy: Always
        name: contour
        command: ["contour"]
        args: ["serve", "--incluster", "--xds-address", "::1", "--envoy-service-http", "::", "--envoy-service-https", "::"]
```
Hope this helps. I don't have an IPv6 enabled cluster so can't really test this out.

**Comment by roshnihp** [comment]
With the changes as stated above pods didnt start and I got error at envoy-initconfig
```
root@master1:/home/roshini# kubectl logs contour-599f8f85b8-mxtvz  -n heptio-contour envoy-initconfig
contour: error: unexpected /config/contour.json, try --help
```
Hence I removed `- xds-address="::1"` from initContainer and tried with only below arguments in container
` args: ["serve", "--incluster", "--xds-address", "::1", "--envoy-service-http-address", "::", "--envoy-service-https-address", "::"]`
Now I can see 8000 is opened.
```
root@master1:/home/roshini# kubectl exec -ti contour-7f7f595db6-6nq9j /bin/sh -n heptio-contour
Defaulting container name to contour.
Use 'kubectl describe pod/contour-7f7f595db6-6nq9j -n heptio-contour' to see all of the containers in this pod.
/ # netstat -putan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      1/contour
tcp        0      0 :::8000                 :::*                    LISTEN      1/contour
tcp        0      0 ::1:8001                :::*                    LISTEN      1/contour
tcp        0      1 2019::1:c0a8:13f:57038  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:13f:57036  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:13f:57044  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:13f:57046  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:13f:57040  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:13f:57042  2019::a00:1:443         SYN_SENT    1/contour
```
This is a good progress. However I still dont see endpoints 
```
root@master1:/home/roshini# kubectl get endpoints -n heptio-contour -o wide
NAME      ENDPOINTS   AGE
contour               8m59s
```
When I checked contour and envoy containers , I can see below error
Envoy container error:
```
 kubectl logs contour-7f7f595db6-6nq9j -n heptio-contour envoy
----
[2019-03-04 17:32:11.633][000001][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
```
Contour container error:
```
 kubectl logs contour-7f7f595db6-6nq9j -n heptio-contour contour
---
E0304 17:33:22.002400       1 reflector.go:205] github.com/heptio/contour/internal/k8s/watcher.go:73: Failed to list *v1.Secret: Get https://[2019::a00:1]:443/api/v1/secrets?limit=500&resourceVersion=0: dial tcp [2019::a00:1]:443: i/o timeout
```

**Comment by roshnihp** [comment]
With the above changes the pods end up in error state 
```
root@master1:/home/roshini#  kubectl get pods -n heptio-contour -o wide
NAME                       READY   STATUS       RESTARTS   AGE   IP                 NODE      NOMINATED NODE   READINESS GATES
contour-5956784978-jtcvd   0/2     Init:Error   3          60s   2019::1:c0a8:141   worker1   <none>           <none>
contour-5956784978-kjndr   0/2     Init:Error   3          60s   2019::1:c0a8:142   worker1   <none>           <none>
```
The logs says as below.
```
root@master1:/home/roshini# kubectl logs contour-5956784978-jtcvd -n heptio-contour envoy-initconfig
contour: error: unexpected /config/contour.json, try --help
```
When I commented ` - xds-address="::1"` from initContainer, pods are running. And the result from one of them as below with 8080 and 8443 are missing
```
root@master1:/home/roshini# kubectl exec -ti contour-7f7f595db6-7pwnt -n heptio-contour /bin/sh
Defaulting container name to contour.
Use 'kubectl describe pod/contour-7f7f595db6-7pwnt -n heptio-contour' to see all of the containers in this pod.
/ # netstat -putan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      1/contour
tcp        0      0 :::8000                 :::*                    LISTEN      1/contour
tcp        0      0 ::1:8001                :::*                    LISTEN      1/contour
tcp        0      1 2019::1:c0a8:143:55900  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:143:55904  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:143:55902  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:143:55894  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:143:55896  2019::a00:1:443         SYN_SENT    1/contour
tcp        0      1 2019::1:c0a8:143:55898  2019::a00:1:443         SYN_SENT    1/contour
```

**Comment by davecheney** [comment]
Thank you everyone for your help.

I want to keep everyone focused on the original issue, which was a lack of
entries in the endpoint object.

Configuring envoy to listen on IPv6 addresses is an important, but
independent, problem, to the one the OP raised.

**Comment by alexbrand** [comment]
I suspect they are related. The contour deployment has a readiness probe on the Envoy container. If the readiness probe is failing, the pod overall is considered "NotReady", and the pod IP address will not show up as a Ready address in the list of Endpoints.

@roshnihp can you provide the output of the following commands?

```
kubectl -n heptio-contour describe endpoints
```

```
kubectl -n heptio-contour describe pod contour
```

re: init container changes - It looks like I missed the `--` for the flag. It should be `- --xds-address="::1"`. To make the readiness probe work, however, I think we also need to make the stats endpoint listen on IPv6. With that said, let's verify first that the readiness probe is the actual issue before making any more changes.

**Comment by uablrek** [comment]
Seems you are correct;
```
vm-004 ~ #  kubectl -n heptio-contour describe endpoints
Name:         contour
Namespace:    heptio-contour
Labels:       <none>
Annotations:  <none>
Subsets:
  Addresses:          <none>
  NotReadyAddresses:  1000::2:b00:303,1000::2:b00:403
  Ports:
    Name   Port  Protocol
    ----   ----  --------
    https  8443  TCP
    http   8080  TCP

Events:  <none>
```

**Comment by uablrek** [comment]
```
# kubectl -n heptio-contour describe pod contour
Name:               contour-788bb8fd5c-hnlb7
Namespace:          heptio-contour
Priority:           0
PriorityClassName:  <none>
Node:               vm-001/1000::1:c0a8:101
Start Time:         Tue, 05 Mar 2019 18:14:15 +0000
Labels:             app=contour
                    pod-template-hash=788bb8fd5c
Annotations:        prometheus.io/format: prometheus
                    prometheus.io/path: /stats
                    prometheus.io/port: 8002
                    prometheus.io/scrape: true
Status:             Running
IP:                 1000::2:b00:103
Controlled By:      ReplicaSet/contour-788bb8fd5c
Init Containers:
  envoy-initconfig:
    Container ID:  cri-o://a536133f9a28ecd5855d260db7dcb3c5f3d7a3e9f9ac3a8e450fb6b488c7f39d
    Image:         gcr.io/heptio-images/contour:master
    Image ID:      gcr.io/heptio-images/contour@sha256:a99d09b98163c5b4d4e01773dbe491b50e99ea98dfdd88773bd0a1307e010b8e
    Port:          <none>
    Host Port:     <none>
    Command:
      contour
    Args:
      bootstrap
      /config/contour.json
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 05 Mar 2019 18:14:29 +0000
      Finished:     Tue, 05 Mar 2019 18:14:29 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /config from contour-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from contour-token-ngtlv (ro)
Containers:
  contour:
    Container ID:  cri-o://41439e63014e79d51bde018a7113d059ee720b19db114ec66dc91980d7c6e5ad
    Image:         gcr.io/heptio-images/contour:master
    Image ID:      gcr.io/heptio-images/contour@sha256:a99d09b98163c5b4d4e01773dbe491b50e99ea98dfdd88773bd0a1307e010b8e
    Port:          <none>
    Host Port:     <none>
    Command:
      contour
    Args:
      serve
      --incluster
    State:          Running
      Started:      Tue, 05 Mar 2019 18:14:31 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from contour-token-ngtlv (ro)
  envoy:
    Container ID:  cri-o://dc22334a45333f845446e73fa961cd966f4226e84dfeafc83b4e8ac7d915d219
    Image:         docker.io/envoyproxy/envoy-alpine:v1.9.0
    Image ID:      docker.io/envoyproxy/envoy-alpine@sha256:05106a4efe5b1818edd6a38f34c6314139fc17f0a5c6d88dac5d52ea3fa23718
    Ports:         8080/TCP, 8443/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      envoy
    Args:
      --config-path /config/contour.json
      --service-cluster cluster0
      --service-node node0
      --log-level info
      --v2-config-only
    State:          Running
      Started:      Tue, 05 Mar 2019 18:14:45 +0000
    Ready:          False
    Restart Count:  0
    Readiness:      http-get http://:8002/healthz delay=3s timeout=1s period=3s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /config from contour-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from contour-token-ngtlv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  contour-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  contour-token-ngtlv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  contour-token-ngtlv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason             Age                From               Message
  ----     ------             ----               ----               -------
  Normal   Scheduled          45s                default-scheduler  Successfully assigned heptio-contour/contour-788bb8fd5c-hnlb7 to vm-001
  Normal   Pulling            43s                kubelet, vm-001    Pulling image "gcr.io/heptio-images/contour:master"
  Normal   Pulled             31s                kubelet, vm-001    Successfully pulled image "gcr.io/heptio-images/contour:master"
  Normal   Created            31s                kubelet, vm-001    Created container envoy-initconfig
  Normal   Started            31s                kubelet, vm-001    Started container envoy-initconfig
  Normal   Pulling            30s                kubelet, vm-001    Pulling image "gcr.io/heptio-images/contour:master"
  Normal   Started            29s                kubelet, vm-001    Started container contour
  Normal   Pulling            29s                kubelet, vm-001    Pulling image "docker.io/envoyproxy/envoy-alpine:v1.9.0"
  Normal   Created            29s                kubelet, vm-001    Created container contour
  Normal   Pulled             29s                kubelet, vm-001    Successfully pulled image "gcr.io/heptio-images/contour:master"
  Normal   Pulled             15s                kubelet, vm-001    Successfully pulled image "docker.io/envoyproxy/envoy-alpine:v1.9.0"
  Normal   Created            15s                kubelet, vm-001    Created container envoy
  Normal   Started            15s                kubelet, vm-001    Started container envoy
  Warning  MissingClusterDNS  13s (x5 over 45s)  kubelet, vm-001    pod: "contour-788bb8fd5c-hnlb7_heptio-contour(7c48c7f3-3f72-11e9-a5e4-000000010001)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
  Warning  Unhealthy          1s (x4 over 10s)   kubelet, vm-001    Readiness probe failed: Get http://[1000::2:b00:103]:8002/healthz: dial tcp [1000::2:b00:103]:8002: connect: connection refused
```

**Comment by uablrek** [comment]
The output above is without any modifications to `contour-deployment-rbac`.

**Comment by alexbrand** [comment]
Thanks for confirming. Looks like we need to make the 8002 port listen on an IPv6 interface. 

We should be able to do that by passing `--stats-address=::` to the bootstrap init container, so that the endpoint listens on all IPv6 interfaces.

The init container should look something like this:
```
      initContainers:
      - image: gcr.io/heptio-images/contour:master
        imagePullPolicy: Always
        name: envoy-initconfig
        command: ["contour"]
        args:
        - bootstrap
        - --xds-address="::1" # Tell envoy to talk to contour over IPv6 localhost
        - --stats-address="::" # Tell envoy to bind all IPv6 interfaces for stats address
        - /config/contour.json
```
(Pardon any errors. I don't have an IPv6 cluster to test this out)

**Comment by davecheney** [comment]
I stand corrected. Thank you for explaining Alex

**Comment by uablrek** [comment]
Got them;
```
# kubectl -n heptio-contour get endpoints
NAME      ENDPOINTS                                                                          AGE
contour   [1000::2:b00:203]:8443,[1000::2:b00:403]:8443,[1000::2:b00:203]:8080 + 1 more...   2m6s
```

It is **not** necessary to change the 127.0.0.1 addresses used inside the pod for communication contour<->envoy. In fact I would suggest that they are kept as-is. The `eth0` interface in the pod have only a ipv6 address but the `lo` device has both ipv4 (127.0.0.0/8) and ipv6 (::1/128).

The *only* necessary configuration to get the endpoints active is for the initContainer;
```
      initContainers:
      - image: heptio-images/contour:master
        imagePullPolicy: Always
        name: envoy-initconfig
        command: ["contour"]
        args:
        - bootstrap
        # Uncomment the statsd-enable to enable statsd metrics
        #- --statsd-enable
        # Uncomment to set a custom stats emission address and port
        - "--stats-address=::"
```
The `-stats-address=::` is uncommented and set to the ipv6-any address. **NOTE**; the string *must* be quoted as shown otherwise it will fail the k8s validation.

**Comment by uablrek** [comment]
There is still problems with the traffic ports. Port 8080 is only opened for ipv4. But that should be tracked in another issue.

**Comment by roshnihp** [comment]
Tested the fix in my local cluster and it works and can see endpoints populated. Thank you for the quick support from everyone.
As mentioned in [Traffic ports open for ipv4 only (0.0.0.0) in an k8s ipv6-only cluster #923](url) it would be good to have a service manifest for IPV6 cluster with all these fixes.

**Comment by davecheney** [comment]
I've reviewed this issue and I don't believe there is anything left to do here. Please comment if you believe this is not correct.

**Comment by lion7** [comment]
Just ran into this same issue and found this as the first hit on Google. Also related to #923 and #5480.

I am using the Contour gateway provisioner and solved it using the config below.
Hopefully this saves people some time figuring out how to make Contour work in an IPv6-only cluster 😄 

```yaml
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour-ipv6
spec:
  runtimeSettings:
    health:
      address: "::"
    metrics:
      address: "::"
    xdsServer:
      address: "::"
    envoy:
      http:
        address: "::"
      https:
        address: "::"
      health:
        address: "::"
      metrics:
        address: "::"
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: contour
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: contour-ipv6
    namespace: projectcontour
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: default
  namespace: projectcontour
spec:
  gatewayClassName: contour
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
```
