### ISSUE TITLE
Traffic ports open for ipv4 only (0.0.0.0) in an k8s ipv6-only cluster

### ISSUE THREAD

**Issue by uablrek** [heptio/contour#923]
**What steps did you take and what happened:**

Deploy contour in a k8s ipv6-only cluster with;
```
kubectl apply -f https://j.hept.io/contour-deployment-rbac
```

Configure some simple http back-end and an "ingress". Login to the contour container and examine the listen ports;
```
kubectl -n heptio-contour exec -c contour -it contour-6d78b6fdd9-cb7nt sh
# netstat -lutn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.1:6060          0.0.0.0:*               LISTEN      
tcp        0      0 :::8000                 :::*                    LISTEN      
tcp        0      0 :::8002                 :::*                    LISTEN      
```

Oh, and ipv6 traffic doesn't work of course.

**What did you expect to happen:**

Traffic port should be open with the ipv6 any-address `::` and ipv6 traffic should work.

**Anything else you would like to add:**

The endpoint-fix in #911 must be applied.

With this configuration;
```
      containers:
      - image: gcr.io/heptio-images/contour:master
        imagePullPolicy: Always
        name: contour
        command: ["contour"]
        args:
        - serve
        - --incluster
        - "--envoy-service-http-address=::"
        - "--envoy-service-https-address=::"
```

it works!

I suggest a new manifest for ipv6 is published like;
```
kubectl apply -f https://j.hept.io/contour-deployment-rbac.ipv6
```

with this update and the one in #911 . The file I used is attached.

**Environment:**

- Contour version:
"master"(?) (the image tag is "master")
- Kubernetes version: (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.205+d9f3e96796e2d1", GitCommit:"d9f3e96796e2d154b1d4caa156ba95ff9b01e5b2", GitTreeState:"clean", BuildDate:"2019-02-22T08:07:36Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.0.205+d9f3e96796e2d1", GitCommit:"d9f3e96796e2d154b1d4caa156ba95ff9b01e5b2", GitTreeState:"clean", BuildDate:"2019-02-22T08:07:06Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
None
- Cloud provider or hardware configuration:
None
- OS (e.g. from `/etc/os-release`):
[xcluster](https://github.com/Nordix/xcluster)

[contour-deployment-rbac.ipv6.txt](https://github.com/heptio/contour/files/2935813/contour-deployment-rbac.ipv6.txt)
