### ISSUE TITLE
Https redirect on PermitInsecure route

### ISSUE THREAD

**Issue by glubo** [heptio/contour#974]
We configured contour/envoy ingress controller following https://github.com/heptio/contour/blob/master/docs/deploy-options.md . Ingressroutes works as expected for https. But when we need one ingressroute that will use http "from outside", we tried to setup `permitInsecure` route but still get http=>https redirect when accessing http:// poc-nginx.example.com/ from outside.

**What did you expect to happen:**
No http =>https redirect on `permitInsecure` route.

**Anything else you would like to add:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-nginx-deployment
  labels:
    app: poc-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-nginx
  template:
    metadata:
      labels:
        app: poc-nginx
    spec:
      containers:
      - name: poc-nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: poc-nginx
spec:
  selector:
    app: poc-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: poc-nginx
spec:
  virtualhost:
    fqdn: poc-nginx.example.com
    tls:
      secretName: devel-ingress-secret
  routes:
    - match: /
      services:
        - name: poc-nginx
          port: 80
          permitInsecure: true
```

**Environment:**

- Contour version: v0.10.0-rc.1
- Kubernetes version: (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: kubeadm 1.11
- Cloud provider or hardware configuration: single node baremetal with metallb
- OS (e.g. from `/etc/os-release`):

**Comment by davecheney** [comment]
Thank you for raising this issue. You have an error in your configuration. `permitInsecure` is a child of `routes`, not `services`.

https://github.com/heptio/contour/blob/master/docs/ingressroute.md#permit-insecure

**Comment by davecheney** [comment]
Please try
```
spec:
  virtualhost:
    fqdn: poc-nginx.example.com
    tls:
      secretName: devel-ingress-secret
  routes:
    - match: /
       permitInsecure: true
      services:
        - name: poc-nginx
          port: 80
```
